all:quick heap insert bubble select shell merge count All
quick:QuickSort.c Stack.c
	gcc $^ -o $@ -g -std=c99
heap:HeapSort.c
	gcc $^ -o $@ -g -std=c99

insert:InsertSort.c
	gcc $^ -o $@ -g -std=c99
bubble:BubbleSort.c
	gcc $^ -o $@ -g -std=c99
select:SelectSort.c
	gcc $^ -o $@ -g -std=c99
shell:ShellSort.c
	gcc $^ -o $@ -g -std=c99
merge:MergeSort.c
	gcc $^ -o $@ -g -std=c99
count:CountSort.c
	gcc $^ -o $@ -g -std=c99
All:allSort.c
	gcc $^ -o $@ -g -std=c99
