test_string:string.cpp
	g++ $^ -o $@ -g -std=c++11
test_copyOnWrite:copyOnWrite.cpp
	g++ $^ -o $@ -g -std=c++11
test_improveDeepCopy:stringDeepCopyImprove.cpp
	g++ $^ -o $@ -g -std=c++11
test_deepCopy:stringDeepCopy.cpp
	g++ $^ -o $@ -g -std=c++11
